=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dc="https://vezel.dev/novadrop/dc" elementFormDefault="qualified" targetNamespace="https://vezel.dev/novadrop/dc/QuestDialog" xsi:schemaLocation="https://vezel.dev/novadrop/dc ../DataCenter.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType dc:keys="huntingZoneId id" name="QuestDialog">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Text" type="QuestDialog_Text" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
    <xs:attribute name="huntingZoneId" type="xs:int" />
    <xs:attribute name="voiceTypeId" type="xs:int" />
  </xs:complexType>
  <xs:element name="QuestDialog" type="QuestDialog" />
  <xs:complexType name="QuestDialog_Text">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Page" type="QuestDialog_Text_Page" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
    <xs:attribute name="huntingZoneId" type="xs:int" />
    <xs:attribute name="prevId" type="xs:int" />
    <xs:attribute name="villagerId" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="QuestDialog_Text_Page">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="social" type="xs:int" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_39_22.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="39" id="22" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="239" id="100" prevId="0" villagerId="1007">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="239" id="2" prevId="0" villagerId="1007">
         
        <Page social="4">Pay attention now. I'm only going to say this once.&lt;BR&gt;&lt;BR&gt;At the central part of the lair, you'll find {@LinkCreature:39#130#arachnen matriarchs}. They aren't the strongest creatures in here, but they have very hard shells, which we can put to good use.&lt;BR&gt;&lt;BR&gt;Collect the shells and deliver them to Paicha at Roughneck Outpost. He'll take it from there.</Page>
    
    </Text>
    <Text huntingZoneId="239" id="3" prevId="2" villagerId="1010">
         
        <Page social="4">Arachnen shells, eh?&lt;BR&gt;&lt;BR&gt;Yes, I can use those to patch some of our heavy armor suits. Appreciate the help!</Page>
    
    </Text>
    <Text huntingZoneId="239" id="4" villagerId="1010">
         
        <Page social="0">Got anything for me?</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_35_93.xml
<?xml version='1.0' encoding='utf-8'?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="35" id="93" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="74" id="100" prevId="0" villagerId="1019">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="74" id="2" prevId="0" villagerId="1019">
         
        <Page social="5">&lt;BR&gt;&lt;BR&gt;Oh, desculpe. Pensei que você tivesse dito algo. Continuo ouvindo coisas ultimamente.&lt;BR&gt;&lt;BR&gt;De qualquer forma, você tem alguns Tenebrara {@LinkCreature:35#20#overseers}, {@LinkCreature:35#18#destroyers} e {@LinkCreature:35#17#dreadweavers} para cuidar. Tente não... o quê? &lt;BR&gt;&lt;BR&gt;Oh... desculpe, outra coisa de novo. De qualquer forma, tente não se divertir demais.&lt;BR&gt;&lt;BR&gt;Fale com...fale com Tesran em Wyrmgorge quando terminar.</Page>
    
    </Text>
    <Text huntingZoneId="235" id="3" prevId="2" villagerId="1015">
         
        <Page social="5">Aqui está sua recompensa.&lt;BR&gt;&lt;BR&gt;Continue assim.</Page>
    
    </Text>
    <Text huntingZoneId="235" id="4" villagerId="1015">
         
        <Page social="0">Você está aqui para receber uma recompensa? Por não ter concluído sua missão? Tente novamente.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_33_34.xml
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" id="34" huntingZoneId="33" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="233" id="100" prevId="0" villagerId="1014">
         
         
        <Page social="0" />
    
    
    </Text>
    <Text huntingZoneId="233" id="2" prevId="0" villagerId="1014">
         
         
        <Page social="4">&lt;PCNAME&gt;, ouvi dizer que você não tem medo de sujar as mãos. Eu tenho um trabalho que envolve mãos sujas.&lt;BR&gt;&lt;BR&gt;Ou dedos, na verdade. E os anéis neles.&lt;BR&gt;&lt;BR&gt;Reconheci um rosto entre os mortos-vivos - um velho companheiro de exército. Não sou sentimental, mas o pai dele era joalheiro, e isso me fez pensar. Quantos mortos-vivos estarão carregando objetos de valor?</Page>
    
    
    </Text>
    <Text huntingZoneId="233" id="3" prevId="2" villagerId="1014">
         
         
        <Page social="4">Ei, essa é uma pilha e tanto! Deixe-me ver...&lt;BR&gt;&lt;BR&gt;Ei, foi essa que eu vi!&lt;BR&gt;&lt;BR&gt;Eu tenho uma companheira em casa... bem, uma companheira em potencial, pelo menos. Esse é o tipo de coisa com a qual posso selar o acordo, se é que você me entende.&lt;BR&gt;&lt;BR&gt;Não pode ser! É claro que não vou lhe dizer onde consegui isso. Meu pequeno segredo.</Page>
    
    
    </Text>
    <Text huntingZoneId="233" id="4" villagerId="1014">
         
         
        <Page social="0">Verifique o porão. Há muitos cadáveres assustadores lá embaixo.</Page>
    
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_6_93.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="6" id="93" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="206" id="100" prevId="0" villagerId="1021">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="206" id="2" prevId="0" villagerId="1021">
         
        <Page social="0">The bear population is becoming, well, unbearable. They've got to go.&lt;BR&gt;&lt;BR&gt;Hunt some {@LinkCreature:6#2041#ravenous bears} and thin out their numbers.&lt;BR&gt;&lt;BR&gt;Report to Miljean at Vindicator Camp when your mission is complete.</Page>
    
    </Text>
    <Text huntingZoneId="206" id="3" prevId="2" villagerId="1009">
         
        <Page social="5">Thank you for your hard work!</Page>
    
    </Text>
    <Text huntingZoneId="206" id="4" villagerId="1009">
         
        <Page social="0">It doesn't look like you've completed your mission yet.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_47_22.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="47" id="22" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="77" id="100" prevId="0" villagerId="1010">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="77" id="2" prevId="0" villagerId="1010">
         
        <Page social="4">I don't know if it's a good idea, but due to the shortage of rations around here, folks are talking about eating {@Creature:47#1001$$Tirkai grizzly} meat.&lt;BR&gt;&lt;BR&gt;I guess if we salted it enough it would likely eliminate any argon contamination.&lt;BR&gt;&lt;BR&gt;Take some to Jadora at Field Base Lunacy. She has access to lots of salt.</Page>
    
    </Text>
    <Text huntingZoneId="247" id="3" prevId="2" villagerId="1001">
         
        <Page social="4">She thinks salt will make it safe, huh? We could sure use an alternate source of food around here. I'll give it a go.</Page>
    
    </Text>
    <Text huntingZoneId="247" id="4" villagerId="1001">
         
        <Page social="0">I have salt. What did you say you need it for? I don't see any meat.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_63_33.xml
<?xml version='1.0' encoding='utf-8'?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="63" id="33" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="63" id="100" prevId="0" villagerId="3005">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="63" id="2" prevId="0" villagerId="3005">
         
        <Page social="5">A menos que você tenha um pedaço de couro eldritch escondido em algum lugar, nem pergunte. Não posso fazer as cartolas sem o couro, e o couro não pode ser encontrado em lugar nenhum.&lt;NEXTPAGEBUTTON&gt;&amp;quot;Eu tenho o couro.&amp;quot;&lt;/NEXTPAGEBUTTON&gt;</Page>
    
    </Text>
    <Text huntingZoneId="63" id="3" prevId="2" villagerId="3005">
         
        <Page social="5">Uau, você realmente tinha algum? &lt;BR&gt;&lt;BR&gt;Bem, tudo bem, então! Que chapéu espetacular combina melhor com você? &lt;NEXTPAGEBUTTON&gt;&amp;quot;Deixe-me ver sua seleção.</Page>
    
    </Text>
    <Text huntingZoneId="63" id="4" villagerId="3005">
         
        <Page social="0">Se você precisa de couro eldritch, está sem sorte. Confie em mim, apenas jogue seu couro de sangue e couro bruto no mercado e corte suas perdas.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_4_95.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="4" id="95" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="61" id="100" prevId="0" villagerId="1016">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="61" id="2" prevId="0" villagerId="1016">
         
        <Page social="4">The shurians and their blasted allies are wreaking havoc. We need you to put an end to their efforts.&lt;BR&gt;&lt;BR&gt;The {@LinkCreature:4#3031#tyraks}, {@LinkCreature:4#3041#shurian mindbenders}, and {@LinkCreature:4#3042#hellion thralls} must be slain.&lt;BR&gt;&lt;BR&gt;Report to Tifane at Firebase Valor when mission is complete.</Page>
    
    </Text>
    <Text huntingZoneId="204" id="3" prevId="2" villagerId="1006">
         
        <Page social="4">You've done really wonderful work here. We appreciate the help!</Page>
    
    </Text>
    <Text huntingZoneId="204" id="4" villagerId="1006">
         
        <Page social="0">You came to help, I assume? Maybe you should get to that.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_2_40.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="2" id="40" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="202" id="100" prevId="0" villagerId="1034">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="202" id="2" prevId="0" villagerId="1034">
         
        <Page social="0">Even the unicorns have been corrupted by the ill wind that blows through the Fey Forest. I know Lillix had some luck helping Seravy, but the other unicorns are too fragile to survive such a transition.&lt;BR&gt;&lt;BR&gt;I see your eyes, &lt;PCCLASS:lcase&gt;. You think we don't realize how tragic it is to kill the {@LinkCreature:2#6#sullen} and {@LinkCreature:2#56#feral} unicorns? The only thing more tragic...is to let them live.</Page>
    
    </Text>
    <Text huntingZoneId="202" id="3" prevId="2" villagerId="1034">
         
        <Page social="4">The unicorns' pure spirits could not endure such corruption. But they say a little bit of each unicorn remains in its horn.&lt;BR&gt;&lt;BR&gt;Who knows? In time perhaps we can coax those spirits out of those horns and give them a way to gallop through the forest again!</Page>
    
    </Text>
    <Text huntingZoneId="202" id="4" villagerId="1034">
         
        <Page social="0">Bring back the unicorns' horns, &lt;PCNAME&gt;...after you've done what must be done.</Page>
    
    </Text>
</QuestDialog>
