=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dc="https://vezel.dev/novadrop/dc" elementFormDefault="qualified" targetNamespace="https://vezel.dev/novadrop/dc/QuestDialog" xsi:schemaLocation="https://vezel.dev/novadrop/dc ../DataCenter.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType dc:keys="huntingZoneId id" name="QuestDialog">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Text" type="QuestDialog_Text" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
    <xs:attribute name="huntingZoneId" type="xs:int" />
    <xs:attribute name="voiceTypeId" type="xs:int" />
  </xs:complexType>
  <xs:element name="QuestDialog" type="QuestDialog" />
  <xs:complexType name="QuestDialog_Text">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Page" type="QuestDialog_Text_Page" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
    <xs:attribute name="huntingZoneId" type="xs:int" />
    <xs:attribute name="prevId" type="xs:int" />
    <xs:attribute name="villagerId" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="QuestDialog_Text_Page">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="social" type="xs:int" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_36_37.xml
<?xml version='1.0' encoding='utf-8'?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="36" id="37" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="236" id="100" prevId="0" villagerId="1017">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="236" id="2" prevId="0" villagerId="1017">
         
        <Page social="5">Você já ouviu falar que Killian está fazendo uma lavagem cerebral nos mercenários de Tenebrara, certo? &lt;BR&gt;&lt;BR&gt;Bem, assim que conseguimos controlar essa situação, ele intensificou seu jogo.&lt;BR&gt;&lt;BR&gt;É difícil, mas até agora, estamos aguentando.&lt;BR&gt;&lt;BR&gt;Agora ele transformou os lanceiros e feiticeiros, então os mais poderosos são também os mais perigosos para nós.&lt;BR&gt;&lt;BR&gt;Você pode nos ajudar?</Page>
    
    </Text>
    <Text huntingZoneId="236" id="3" prevId="2" villagerId="1017">
         
        <Page social="18">Não tenho palavras para descrever a pressão que você aliviou. Obrigado, &lt;PCNAME&gt;.&lt;BR&gt;&lt;BR&gt;E aqui está algo para você.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/loc_POR/QuestDialog/QuestDialog_20_92.xml
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" id="92" huntingZoneId="20" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="65" id="100" prevId="0" villagerId="1012">
         
         
        <Page social="0" />
    
    
    </Text>
    <Text huntingZoneId="65" id="2" prevId="0" villagerId="1012">
         
         
        <Page social="0">Tenho ordens suficientes para continuar distribuindo por dias, &lt;PCNAME&gt;.&lt;BR&gt;&lt;BR&gt;Em seguida, parece que eles precisam que você cuide dos {@LinkCreature:20#30114001#ossugon centurions}, {@LinkCreature:20#30114002#ossugon prefects} e {@LinkCreature:20#30114003#ossugon primuses}. Eles estarão nos Salões das Sombras, bloqueando o caminho para o nível mais baixo.&lt;BR&gt;&lt;BR&gt;Encontre-se com Pelsus quando terminar. Ele está em... vamos ver... sim, nos Salões da Escuridão.</Page>
    
    
    </Text>
    <Text huntingZoneId="220" id="3" prevId="2" villagerId="1004">
         
         
        <Page social="4">Bom trabalho! Adoro ver nossos soldados tão ansiosos para se mexer! &lt;BR&gt;&lt;BR&gt;Aqui está sua recompensa.</Page>
    
    
    </Text>
    <Text huntingZoneId="220" id="4" villagerId="1004">
         
         
        <Page social="0">Você tem negócios aqui?</Page>
    
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_172_8.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="172" id="8" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="172" id="100" prevId="0" villagerId="1000">
         
        <Page social="0">The Vanguard Initiatve suffered a major loss. You help take stock before continuing with the mission.</Page>
    
    </Text>
    <Text huntingZoneId="172" id="2" prevId="0" villagerId="1000">
         
        <Page social="4">Most of the Vanguards escaped, thanks to you. Still, things look bad for our mission.&lt;NEXTPAGEBUTTON&gt;"How can I help?"&lt;/NEXTPAGEBUTTON&gt;</Page>
         
        <Page social="0">We should secure our supplies before something awful eats them. Without the sky cruiser, who knows when we'll get resupplied.&lt;BR&gt;&lt;BR&gt;Can you help get the supplies to Dougal?</Page>
    
    </Text>
    <Text huntingZoneId="172" id="3" prevId="2" villagerId="1001">
         
        <Page social="4">Well done, &lt;PCNAME&gt;.&lt;BR&gt;&lt;BR&gt;Well, we made it to Northern Arun, so we can still complete our mission.&lt;BR&gt;&lt;BR&gt;Ask Zolyn how the troops are. We need to know our fighting capability before we move out.</Page>
    
    </Text>
    <Text huntingZoneId="172" id="4" villagerId="1001">
         
        <Page social="0">Is this all? Really?</Page>
    
    </Text>
    <Text huntingZoneId="172" id="5" prevId="3" villagerId="1002">
         
        <Page social="4">Damn it, &lt;PCNAME&gt;! I'm a reaper, not a doctor.&lt;BR&gt;&lt;BR&gt;Check on the wounded yourself. I'm looking for Syona's trail!</Page>
    
    </Text>
    <Text huntingZoneId="172" id="6" prevId="5" villagerId="1003">
         
        <Page social="4">My leg! I think my ankle's shattered. Is bone supposed to stick out?&lt;BR&gt;&lt;BR&gt;Help me!</Page>
    
    </Text>
    <Text huntingZoneId="172" id="7" prevId="6" villagerId="1004">
         
        <Page social="4">Augh, it hurts when I breathe. Blast! What's the point?&lt;BR&gt;&lt;BR&gt;We're never getting home, are we?</Page>
    
    </Text>
    <Text huntingZoneId="172" id="8" prevId="7" villagerId="1002">
         
        <Page social="4">Tysan's injury will slow us down. I'll order Paesyn to make a litter to carry him.&lt;BR&gt;&lt;BR&gt;Broderik's just going to work through his. No one goes home until we find Syona!</Page>
    
    </Text>
    <Text huntingZoneId="172" id="9" prevId="8" villagerId="1001">
         
        <Page social="4">The injuries could have been much worse. We'll count our blessings.&lt;BR&gt;&lt;BR&gt;Fine work. Just like old times, eh?</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_25_35.xml
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" id="35" huntingZoneId="25" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="225" id="100" prevId="0" villagerId="1027">
         
         
        <Page social="0" />
    
    
    </Text>
    <Text huntingZoneId="225" id="2" prevId="0" villagerId="1027">
         
         
        <Page social="4">Tenho uma missão altamente confidencial para você. Preciso que você encontre uma pessoa: Jacobi.&lt;NEXTPAGEBUTTON&gt;"Onde posso encontrá-lo?"&lt;/NEXTPAGEBUTTON&gt;</Page>
         
         
        <Page social="4">Está vendo o canal do lado de fora? Há uma passagem secreta ao lado dele. Ele está se escondendo lá. Seja discreto.</Page>
    
    
    </Text>
    <Text huntingZoneId="225" id="3" prevId="2" villagerId="1028">
         
         
        <Page social="4">Rendalf o enviou? Você deve estar aqui para ajudar na minha investigação. Eu estava esperando por alguém.</Page>
    
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/loc_POR/QuestDialog/QuestDialog_33_36.xml
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" id="36" huntingZoneId="33" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="233" id="100" prevId="0" villagerId="1008">
         
         
        <Page social="0" />
    
    
    </Text>
    <Text huntingZoneId="233" id="2" prevId="0" villagerId="1008">
         
         
        <Page social="4">Chega de lutar corredor por corredor, escada por escada. É hora de aplicar um pouco de engenhosidade de Mysterium ao problema.&lt;BR&gt;&lt;BR&gt;Tome este scrambler. Instale-o em cada um dos três dispositivos de êxtase... na ordem certa.&lt;BR&gt;&lt;BR&gt;Isso deve privar seus fantasmas invisíveis de energia. E com os fantasmas fora de cena, Thulsa perderá o controle sobre os mortos-vivos.</Page>
    
    
    </Text>
    <Text huntingZoneId="233" id="3" prevId="2" villagerId="1015">
         
         
        <Page social="0">(Você instala o codificador. O dispositivo de êxtase para de zumbir, geme como se estivesse vivo e depois fica em silêncio. A atmosfera nesta câmara parece menos sufocante).</Page>
    
    
    </Text>
    <Text huntingZoneId="233" id="4" prevId="3" villagerId="1016">
         
         
        <Page social="0">(Você instala o codificador. O dispositivo de êxtase para de zumbir, geme como se estivesse vivo e depois fica em silêncio. A atmosfera nesta câmara parece menos sufocante).</Page>
    
    
    </Text>
    <Text huntingZoneId="233" id="5" prevId="4" villagerId="1017">
         
         
        <Page social="0">(Você instala o codificador. O dispositivo de êxtase para de zumbir, geme como se estivesse vivo e depois fica em silêncio. A atmosfera nesta câmara parece menos sufocante).</Page>
    
    
    </Text>
    <Text huntingZoneId="233" id="6" prevId="5" villagerId="1008">
         
         
        <Page social="4">Agora Thulsa terá grande dificuldade em dar aos mortos-vivos o poder necromântico de que precisam.&lt;BR&gt;&lt;BR&gt;Uma vitória impecável, &lt;PCNAME&gt;.</Page>
    
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_42_1.xml
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" id="1" huntingZoneId="42" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="0" id="100" prevId="0" villagerId="0">
         
         
        <Page social="0">Você foi ao Templo de Dagon por ordem de Fraya e encontrou lá a equipe de expedição em busca de um suposto tesouro que ajudaria a financiar os custos da Guerra de Argon.&lt;BR&gt;&lt;BR&gt;Depois de uma busca exaustiva no templo, você obteve a Gema Cerúlea, chave para a ressurreição de Dagon, e a entregou à equipe de expedição.</Page>
    
    
    </Text>
    <Text huntingZoneId="0" id="2" prevId="0" villagerId="0">
         
         
        <Page social="5">Ordens de Missão&lt;BR&gt;&lt;BR&gt;O Comandante Fraya solicitou sua ajuda em um assunto de interesse da equipe de expedição do Templo de Dagon. Consulte Ibar em Frontera para obter detalhes.</Page>
    
    
    </Text>
    <Text huntingZoneId="75" id="3" prevId="2" villagerId="1001">
         
         
        <Page social="5">Estou feliz por você estar aqui, &lt;PCNAME&gt;. Não me pergunte como sabemos disso, mas os nagas têm escondido um tesouro em algum lugar do Templo de Dagon, presumivelmente para usá-lo como oferenda.&lt;BR&gt;&lt;BR&gt;Temos um uso melhor para ele. Os argons não vão a lugar algum e o tesouro está se esgotando. A federação está procurando... soluções criativas.&lt;BR&gt;&lt;BR&gt;Enviamos uma equipe de expedição para vasculhar o templo, mas eles vão precisar de reforços. Eu gostaria de enviar você.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="4" prevId="3" villagerId="1039">
         
         
        <Page social="5">Você não pode saber o quanto estamos gratos por vê-lo aqui. Não apenas o templo é muito maior do que esperávamos, mas os nagas e seus amigos estão se mostrando inimigos formidáveis.&lt;BR&gt;&lt;BR&gt;Pelo que conseguimos descobrir, há dois esconderijos de tesouro em dois andares diferentes. Um está em algum lugar perto daqui, e o outro - o grande - está lá embaixo, onde Dagon está dormindo.&lt;BR&gt;&lt;BR&gt;Receio que não saibamos mais do que isso, mas precisamos desses tesouros, &lt;PCNAME&gt;. A federação precisa deles.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="5" prevId="4" villagerId="1039">
         
         
        <Page social="4">Você trouxe o tesouro! Vamos ver o que há aqui! &lt;NEXTPAGEBUTTON&gt;"Algo valioso?"&lt;/NEXTPAGEBUTTON&gt;</Page>
         
         
        <Page social="4">Sim, mas não tanto quanto esperávamos. Temos que encontrar aquele tesouro inferior - isso dificilmente será suficiente para comprar cem armaduras boas.&lt;BR&gt;&lt;BR&gt;Há outro acampamento no próximo nível abaixo. Fale com Wekrine lá embaixo - eles estão formulando planos para chegar aos níveis mais baixos.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="6" villagerId="1039">
         
         
        <Page social="0">Você já encontrou o tesouro?</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="7" prevId="5" villagerId="1040">
         
         
        <Page social="5">Nedisia o enviou? Excelente. Já percorremos todos os cantos desse nível sem encontrar nada.&lt;BR&gt;&lt;BR&gt;Pode o &lt;PCNAME&gt;controlar os templários de Dagonite na Câmara das Almas Poderosas? E trazer de volta um pouco de couro de naga.&lt;NEXTPAGEBUTTON&gt;"Couro de naga?"&lt;/NEXTPAGEBUTTON&gt;</Page>
         
         
        <Page social="4">Sim, a pele é resistente o suficiente para ser transformada em uma armadura e também tem propriedades mágicas. É vendida por um preço alto em Allemantheia.&lt;BR&gt;&lt;BR&gt;Como você vai lutar contra eles de qualquer maneira, não há necessidade de desperdiçar a oportunidade de enriquecer os cofres da federação.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="8" prevId="7" villagerId="1040">
         
         
        <Page social="4">Elas são requintadas. E o dinheiro que recebermos com a venda deles ajudará no esforço de guerra. Muito bem, &lt;PCNAME&gt;.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="9" villagerId="1040">
         
         
        <Page social="0">Você trouxe o couro de naga?</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="10" prevId="8" villagerId="1038">
         
         
        <Page social="5">Couro de naga, diz ela. Sim, é terrivelmente caro, mas não fará diferença no custo dessa guerra.&lt;BR&gt;&lt;BR&gt;Mas acredito que a Gema Cerúlea esteja aqui neste templo. Ela não é apenas a coisa mais valiosa que poderíamos esperar encontrar, mas os mekonaris acham que ela acelerará o processo de ressurreição de Dagon. Isso significa que devemos mantê-la longe deles.&lt;BR&gt;&lt;BR&gt;Também pode haver mais tesouros. Mantenham seus olhos abertos.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="11" prevId="10" villagerId="1038">
         
         
        <Page social="4">Dê uma olhada nisso! Magníficas! Valem bilhões de peças de couro naga.&lt;BR&gt;&lt;BR&gt;A propósito, &lt;PCNAME&gt;, meu batedor diz que os nagas esconderam a Relíquia de Dagon na Chantry de Dagon. Se isso for verdade, eles podem estar se preparando para ressuscitá-lo.&lt;BR&gt;&lt;BR&gt;Temos que pegar essa gema.&lt;NEXTPAGEBUTTON&gt;"O que posso fazer?"&lt;/NEXTPAGEBUTTON&gt;</Page>
         
         
        <Page social="4">Temos quase certeza de que o Chantry de Dagon fica no fundo do templo, mas não temos ideia de onde. &lt;BR&gt;&lt;BR&gt;Um dos mekonaris - Resaltuuk, o Sacerdote da Renovação - tem um livro que diz a localização exata. Você provavelmente terá que pegá-lo de seu cadáver.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="12" villagerId="1038">
         
         
        <Page social="0">Vamos ver o que há aqui, certo?</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="13" prevId="11" villagerId="1038">
         
         
        <Page social="4">O Livro dos Rituais! Agora podemos encontrar o Chantry de Dagon!&lt;BR&gt;&lt;BR&gt;Sim, aqui. Mas está protegido de alguma forma.&lt;BR&gt;&lt;BR&gt;Olha, há um menir no salão central do terceiro nível. Talvez seja assim que eles entram e saem.&lt;BR&gt;&lt;BR&gt;Quando você entrar, &lt;PCNAME&gt;, não espere que seja fácil. Eles terão seus guerreiros mais poderosos guardando o local. Derrote-os e procure a gema na sala.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="14" villagerId="1038">
         
         
        <Page social="0">O Livro dos Rituais. Você já o tem? &lt;BR&gt;&lt;BR&gt;Não podemos encontrar o Chantry de Dagon sem ele.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="15" prevId="13" villagerId="1038">
         
         
        <Page social="4">Então é isso: a Gema Cerúlea. Essa pedra preciosa sozinha é igual a todas as riquezas de Allemantheia.&lt;BR&gt;&lt;BR&gt;E há um poder inegável aqui também. O Mysterium ficará muito interessado.&lt;BR&gt;&lt;BR&gt;Agora a federação terá os meios para combater os argons, e devemos isso a você, &lt;PCNAME&gt;. Este estava entre os tesouros que libertamos, e eu gostaria que você ficasse com ele. É pouco em comparação com o que você fez, mas espero que você encontre algum valor nele. Use-o bem.</Page>
    
    
    </Text>
    <Text huntingZoneId="242" id="16" villagerId="1038">
         
         
        <Page social="0">Você encontrou a Cerulean Gem? Ela estava lá?</Page>
    
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_22_35.xml
<?xml version='1.0' encoding='utf-8'?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="22" id="35" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="222" id="100" prevId="0" villagerId="1023">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="222" id="2" prevId="0" villagerId="1023">
         
        <Page social="5">Nas profundezas das Catacumbas da Rainha das Bruxas, {@LinkCreature:22#21#chaos guides} e seus {@LinkCreature:22#22#iskaragards} estão trabalhando contra nós.&lt;BR&gt;&lt;BR&gt;Minhas irmãs precisam ser detidas. Elas conhecem melhor nossas táticas, por isso preciso pedir que você as enfrente.</Page>
    
    </Text>
    <Text huntingZoneId="222" id="3" prevId="2" villagerId="1023">
         
        <Page social="5">Tudo o que peço é que, quando tivermos resolvido esse caso miserável, entendamos como isso aconteceu e quem o ordenou.&lt;BR&gt;&lt;BR&gt;O entendimento me ajudará a me curar e saber quem é o responsável dará aos bruxos sobreviventes alguém para matar. Lentamente.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_55_31.xml
<?xml version='1.0' encoding='utf-8'?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="55" id="31" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="255" id="100" prevId="0" villagerId="1015">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="255" id="2" prevId="0" villagerId="1015">
         
        <Page social="4">O caminho para o Cajado de Isren está bloqueado por orisks. Eles normalmente não são encontrados nessa área, então alguém quer que fiquemos o mais longe possível do cajado.&lt;BR&gt;&lt;BR&gt;Precisamos chegar ao cajado. Não me importa se você os atrai com bolinhos de vapor e uísque de fogo, mas vivos ou mortos, eles têm que ir.</Page>
    
    </Text>
    <Text huntingZoneId="255" id="3" prevId="2" villagerId="1015">
         
        <Page social="4">Ainda bem que você não desperdiçou comida ou bebida com os oriscos. As rações estão um pouco escassas ultimamente. As pessoas poderiam tê-lo matado por causa do uísque de fogo.</Page>
    
    </Text>
</QuestDialog>
