=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dc="https://vezel.dev/novadrop/dc" elementFormDefault="qualified" targetNamespace="https://vezel.dev/novadrop/dc/QuestDialog" xsi:schemaLocation="https://vezel.dev/novadrop/dc ../DataCenter.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType dc:keys="huntingZoneId id" name="QuestDialog">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Text" type="QuestDialog_Text" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
    <xs:attribute name="huntingZoneId" type="xs:int" />
    <xs:attribute name="voiceTypeId" type="xs:int" />
  </xs:complexType>
  <xs:element name="QuestDialog" type="QuestDialog" />
  <xs:complexType name="QuestDialog_Text">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Page" type="QuestDialog_Text_Page" />
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" />
    <xs:attribute name="huntingZoneId" type="xs:int" />
    <xs:attribute name="prevId" type="xs:int" />
    <xs:attribute name="villagerId" type="xs:int" />
  </xs:complexType>
  <xs:complexType name="QuestDialog_Text_Page">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="social" type="xs:int" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== gianpelisser/NovaTera_PT-BR/loc_POR/QuestDialog/QuestDialog_28_93.xml
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" id="93" huntingZoneId="28" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="70" id="100" prevId="0" villagerId="1017">
         
         
        <Page social="0" />
    
    
    </Text>
    <Text huntingZoneId="70" id="2" prevId="0" villagerId="1017">
         
         
        <Page social="0">Esses malditos ataques de oriscos estão prejudicando os esforços de recuperação. Não vou permitir isso. Mate {@LinkCreature:28#3021#reeking orisks} e recolha suas carapaças. Sinta-se à vontade para fazê-los sofrer um pouco.&lt;BR&gt;&lt;BR&gt;Relate a Laneama quando a missão estiver concluída.</Page>
    
    
    </Text>
    <Text huntingZoneId="228" id="3" prevId="2" villagerId="1004">
         
         
        <Page social="5">Um bom trabalho merece ser recompensado. Obrigado a você.</Page>
    
    
    </Text>
    <Text huntingZoneId="228" id="4" villagerId="1004">
         
         
        <Page social="0">Até que os oriscos sejam repelidos, não vou entregar a recompensa.</Page>
    
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_121_16.xml
<?xml version='1.0' encoding='utf-8'?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="121" id="16" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="63" id="100" prevId="0" villagerId="22002">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="63" id="2" prevId="0" villagerId="22002">
         
        <Page social="1">O que precisamos é de troféus de escalão. Infelizmente, você precisará se espalhar pelo mundo para encontrá-los.&lt;BR&gt;&lt;BR&gt;Tente estes lugares:&lt;BR&gt;&lt;BR&gt;Balder's Temple (Normal)-{@linkcreature:425#8005#Auricadis}&lt;BR&gt;Balder's Temple (1 pessoa)-{@linkcreature:825#6000#Nightmare Glaciernus}&lt;BR&gt;Manaya's Core-{@linkcreature:727#2007#Shandra Manaya}</Page>
    
    </Text>
    <Text huntingZoneId="63" id="3" prevId="2" villagerId="22002">
         
        <Page social="4">Que bom - esse token nos ajudará a nos tornarmos a potência mais rica que este mundo já viu!</Page>
    
    </Text>
    <Text huntingZoneId="63" id="4" villagerId="22002">
         
        <Page social="0">Para obter lucro!</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/loc_POR/QuestDialog/QuestDialog_182_1.xml
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" id="1" huntingZoneId="182" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="182" id="100" prevId="0" villagerId="2029">
         
         
        <Page social="0">Enquanto perseguia Mihog, &lt;PCNAME&gt; descobriu que os demokrons eram, na verdade, Parthians, que foram transformados após experimentos cruéis.&lt;BR&gt;Enfurecido, o comandante Rhodos, de Khirian, jurou vingança.</Page>
    
    
    </Text>
    <Text huntingZoneId="182" id="2" prevId="0" villagerId="2029">
         
         
        <Page social="1">(Este barril é muito limpo em comparação com os barris empoeirados ao redor. E parece que alguém o moveu recentemente.)&lt;NEXTPAGEBUTTON&gt;Mover o barril&lt;/NEXTPAGEBUTTON&gt;</Page>
    
    
    </Text>
    <Text huntingZoneId="822" id="3" prevId="2" villagerId="2003">
         
         
        <Page social="1">Feiticeiro Arcdeva? Ela passou correndo por mim, com Zolyn e os popori logo atrás dela!&lt;NEXTPAGEBUTTON&gt;"Ok, obrigado."&lt;/NEXTPAGEBUTTON&gt;</Page>
    
    
    </Text>
    <Text huntingZoneId="822" id="4" prevId="3" villagerId="2012">
         
         
        <Page social="1">Zolyn foi atrás dela. Se você se apressar, poderá alcançá-la e matar aquela maldita arquideva! &lt;NEXTPAGEBUTTON&gt;"E quanto a Rhodos?"&lt;/NEXTPAGEBUTTON&gt;</Page>
         
         
        <Page social="1">Eu falarei com Rhodos... para acalmá-lo. Preocupe-se com o Feiticeiro Arcdeva! &lt;NEXTPAGEBUTTON&gt;"Considere isso feito!"&lt;/NEXTPAGEBUTTON&gt;</Page>
    
    
    </Text>
    <Text huntingZoneId="182" id="5" prevId="4" villagerId="2010">
         
         
        <Page social="1">Esse palhaço excessivamente cauteloso suspeitou de uma armadilha e não me deixou passar! Agora perdemos o rastro do Feiticeiro Arcdeva.&lt;NEXTPAGEBUTTON&gt;"Não o culpe muito."&lt;/NEXTPAGEBUTTON&gt;</Page>
    
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_30_46.xml
<?xml version='1.0' encoding='utf-8'?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="30" id="46" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="230" id="100" prevId="0" villagerId="1047">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="230" id="2" prevId="0" villagerId="1047">
         
        <Page social="1">O clã Consos vive no Refúgio de Balder há séculos. Impérios se ergueram e caíram ao nosso redor, mas nunca deixamos este lugar.&lt;BR&gt;&lt;BR&gt;Tenho alguma noção do que aconteceu no mundo exterior, mas meu conhecimento do que você chamaria de "eventos atuais" é lamentavelmente inadequado.&lt;BR&gt;&lt;BR&gt;Caminhe entre as pessoas, &lt;PCNAME&gt;, e ouça suas histórias. Faça um relatório para mim, mas primeiro: ouça de verdade.</Page>
    
    </Text>
    <Text huntingZoneId="230" id="3" prevId="2" villagerId="1037">
         
        <Page social="1">Nandu quer uma recontagem da história popori desde a morte do deus Balder? Ele tem um mês livre? &lt;BR&gt;&lt;BR&gt;Muito bem. Diga a ele o seguinte. A realeza elin nos leva de {@Rgn:68001$$Pora Elinu}. Rida, uma das princesas, esteve no refúgio de Balder recentemente, e talvez Nandu a tenha conhecido.&lt;NEXTPAGEBUTTON&gt;"Conte-me mais."&lt;/NEXTPAGEBUTTON&gt;</Page>
         
        <Page social="1">Bem, a deusa Elinu nos escondeu do mundo por séculos, mas depois desapareceu. Nós deveríamos saber melhor do que ninguém: ninguém pode se isolar como Elinu. Os popori e os elin se uniram à federação assim que soubemos que os argons estavam destruindo o mundo, não apenas conquistando-o.</Page>
    
    </Text>
    <Text huntingZoneId="230" id="4" prevId="2" villagerId="1036">
         
        <Page social="1">A história dos altos elfos deve ser bem conhecida, mesmo para um recluso como Nandu.&lt;BR&gt;&lt;BR&gt;Talvez ele busque a perspectiva de um High Elf erudito, no entanto, em vez de ouvir contos de glória de segunda mão. Que assim seja.&lt;BR&gt;&lt;BR&gt;&lt;NEXTPAGEBUTTON&gt;"Apenas um resumo, por favor."&lt;/NEXTPAGEBUTTON&gt;</Page>
         
        <Page social="1">A sociedade élfica floresceu e era invejada pelo mundo, até que um acidente fez com que a Flor da Vida, a fonte de todo o poder de Allemantheia, saísse do controle.&lt;BR&gt;&lt;BR&gt;Somente o sacrifício da maior mente élfica fez com que a magia voltasse a ficar sob controle, na forma de um artefato vivo chamado Núcleo.&lt;BR&gt;&lt;BR&gt;Hoje os altos elfos são uma das muitas raças da Federação Valkyon, mas, como sempre, os elfos lideram pelo exemplo. Meu povo corrige nossos irmãos menos refinados com gentileza e delicadeza.</Page>
    
    </Text>
    <Text huntingZoneId="230" id="5" prevId="2" villagerId="1034">
         
        <Page social="1">Nandu sabe que os deuses frequentemente lutam contra os deuses. Durante séculos, ele viveu onde o mais nobre dos deuses, Balder, morreu nas mãos de seus inimigos divinos.&lt;BR&gt;&lt;BR&gt;Depois da Guerra Divina, os deuses sobreviventes estavam todos a salvo. Até recentemente.&lt;BR&gt;&lt;BR&gt;Mas agora... Akasha? Morto. Killian? Morto. Thulsa? Morta. Todos pelas mãos do mesmo mortal. Não é verdade, &lt;PCNAME&gt;?&lt;NEXTPAGEBUTTON&gt;"Eu não agi sozinho."&lt;/NEXTPAGEBUTTON&gt;</Page>
         
        <Page social="1">Você está sendo modesto ou cauteloso, eu me pergunto?&lt;BR&gt;&lt;BR&gt;Você não precisa se revelar, mas poderia mencionar a Nandu que todos - o Mysterium, a federação, os argons, os próprios deuses - estão observando o mortal que matou aqueles deuses.&lt;BR&gt;&lt;BR&gt;Eu me pergunto como esse mortal assassino de deuses resiste a tal escrutínio. Mas aposto que você não precisa se perguntar, não é mesmo?</Page>
    
    </Text>
    <Text huntingZoneId="230" id="6" prevId="3" villagerId="1047">
         
        <Page social="1">Três contos de três contadores de histórias. Uma interessante lição de atualidades para mim.&lt;BR&gt;&lt;BR&gt;E uma interessante lição de psicologia para você.&lt;NEXTPAGEBUTTON&gt;"Como assim?"&lt;/NEXTPAGEBUTTON&gt;</Page>
         
        <Page social="1">Considere o seguinte, &lt;PCNAME&gt;: Os contadores de histórias lhe ensinaram sobre a história ou, inadvertidamente, lhe ensinaram sobre eles mesmos?</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_31_37.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="31" id="37" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="231" id="100" prevId="0" villagerId="1042">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="231" id="2" prevId="0" villagerId="1042">
         
        <Page social="4">It's difficult to detect the silent movements of the {@LinkCreature:31#8#sepulchral wraiths} and {@LinkCreature:31#9#souleater wraiths}. That's one reason they've killed so many. Please eliminate these creatures for the safety of the coastal villagers.</Page>
    
    </Text>
    <Text huntingZoneId="231" id="3" prevId="2" villagerId="1042">
         
        <Page social="4">Good work. You can't imagine how many lives you have saved.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_16_33.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="16" id="33" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="216" id="100" prevId="0" villagerId="1003">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="216" id="2" prevId="0" villagerId="1003">
         
        <Page social="4">I'm hearing rumors from every direction. Something about a &lt;font color='#660000'&gt;Ceremony of Blessing&lt;/font&gt;? And this new camp: &lt;font color='#660000'&gt;Alethea's Last Hope&lt;/font&gt;. I think that should be your next stop.&lt;BR&gt;&lt;BR&gt;Lene headed that way. Maybe she'll know what to do.</Page>
    
    </Text>
    <Text huntingZoneId="216" id="3" prevId="2" villagerId="1023">
         
        <Page social="4">Hmm? Korwyn sent you, did he? Good to know he's all right—I haven't been able to check in with him lately. I ran into federation soldiers, and they brought me here.&lt;NEXTPAGEBUTTON&gt;"Korwyn mentioned a Ceremony of Blessing?"&lt;/NEXTPAGEBUTTON&gt;</Page>
         
        <Page social="4">Ah! He heard that much at least? Good. I'm glad some news is still getting out there. I'll get into the specifics in a bit.&lt;BR&gt;&lt;BR&gt;What you need to know now is that we have uninfected vampirs helping us—Uninfected, so don't go flashing that weapon around, okay?&lt;BR&gt;&lt;BR&gt;We're going to get to the bottom of this, soon.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_ENG/QuestDialog/QuestDialog_52_50.xml
<?xml version="1.0" encoding="utf-8"?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="52" id="50" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="252" id="100" prevId="0" villagerId="1048">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="252" id="2" prevId="0" villagerId="1048">
         
        <Page social="4">Thulsa's dogs have desecrated our holy ground by placing crimson shards throughout it.&lt;BR&gt;&lt;BR&gt;As offensive as they are, however, I must admit they are made out of a fantastic material. Dismantle the crimson shards and bring me the fragments.&lt;BR&gt;&lt;BR&gt;Heh. I'll melt all the fragments down and use them to restore the Divine Furnace once we take it back.&lt;BR&gt;&lt;BR&gt;Clean up the holy ground and get superb materials for free? How can it get any better than that?</Page>
    
    </Text>
    <Text huntingZoneId="252" id="3" prevId="2" villagerId="1048">
         
        <Page social="4">Brilliant work!&lt;BR&gt;&lt;BR&gt;Hmmm... I can still sense traces of Thulsa's magic in these fragments. I will have the Mysterium purify them before I cast them into the furnace.&lt;BR&gt;&lt;BR&gt;I shall now compensate you for your trouble.</Page>
    
    </Text>
    <Text huntingZoneId="252" id="4" villagerId="1048">
         
        <Page social="0">This holy place must be cleared of all traces of those Thulsan and Ksharan dogs!&lt;BR&gt;&lt;BR&gt;Dismantle all the crimson shards in sight and bring me the fragments.</Page>
    
    </Text>
</QuestDialog>

=== gianpelisser/NovaTera_PT-BR/DataCenter_POR/QuestDialog/QuestDialog_55_92.xml
<?xml version='1.0' encoding='utf-8'?>
<QuestDialog xmlns="https://vezel.dev/novadrop/dc/QuestDialog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://vezel.dev/novadrop/dc/QuestDialog QuestDialog.xsd" huntingZoneId="55" id="92" voiceTypeId="0">
    <Text huntingZoneId="0" id="1" prevId="0" villagerId="0" />
    <Text huntingZoneId="80" id="100" prevId="0" villagerId="1012">
         
        <Page social="0" />
    
    </Text>
    <Text huntingZoneId="80" id="2" prevId="0" villagerId="1012">
         
        <Page social="0">As coisas estão difíceis na Floresta de Darkquaver. Parece que tudo se voltou contra nós.&lt;BR&gt;&lt;BR&gt;Preciso que você mate {@LinkCreature:56#16#Hienas de Darkquaver}, {@LinkCreature:56#17#Cavalos-marinhos-de-razortusk}, {@LinkCreature:55#1#Caminhantes-espinhosos-malucos} e {@LinkCreature:55#11#Unicórnios-prateados}.&lt;BR&gt;&lt;BR&gt;Apresentar-se à Belva na Guarnição de Darkquaver quando a missão estiver concluída.</Page>
    
    </Text>
    <Text huntingZoneId="255" id="3" prevId="2" villagerId="1011">
         
        <Page social="4">Você recebeu os agradecimentos da federação!</Page>
    
    </Text>
    <Text huntingZoneId="255" id="4" villagerId="1011">
         
        <Page social="0">Parece que você ainda não completou sua missão.</Page>
    
    </Text>
</QuestDialog>
